# This file was generated by GoReleaser. DO NOT EDIT.
cask "hearthroom" do
  version "0.1.10"

  on_macos do
    on_arm do
      sha256 "cfd0a0b95b3176f50c0222aacf9a14f69160d6ba64cf65c59b52f69e3cd2f451"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "89ae2e29a2bedbb13aacc4c12d643d588e70de2b7f348abb51657681d5a38101"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b3759bf737564cb05afd284b3c5ed623ff2abeedd51774b445f35d23e9afbe5a"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c90557b91c846551415d0b04a8beb8b11c70d4a82ccad8f15ccf1086acbe2acd"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hearthroom"
  desc "Command-line client for Hearthroom character cards"
  homepage "https://hearthroom.club"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hearthroom"
  bash_completion "completions/hearthroom.bash"
  fish_completion "completions/hearthroom.fish"
  zsh_completion "completions/hearthroom.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hearthroom"]
    end
  end

  # No zap stanza required
end
