# This file was generated by GoReleaser. DO NOT EDIT.
cask "hearthroom" do
  version "0.1.7"

  on_macos do
    on_arm do
      sha256 "cfa58fff4db71ac15ce03a60d0a3d288c50273d7a82b51b7c6f6a66875efd646"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "48422e7454d1c2ee08420c0247d62459d8d400d9593f73caa992015386623077"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ccf37b9986b477ccbc02effe8df479d4eb559dc26f0ed0e5060b6d7c98d6a25"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "08ab20b133e14413a40b8ad8ae996ea99b3c9ae13573ee77598ec40d2c3ab165"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hearthroom"
  desc "Command-line client for Hearthroom character cards"
  homepage "https://hearthroom.club"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hearthroom"
  bash_completion "completions/hearthroom.bash"
  fish_completion "completions/hearthroom.fish"
  zsh_completion "completions/hearthroom.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hearthroom"]
    end
  end

  # No zap stanza required
end
