# This file was generated by GoReleaser. DO NOT EDIT.
cask "hearthroom" do
  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "bd2c67f40ce6aa3e330f28096d199e37f35c00d4188be45103fe0d27a693c9e5"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "63a182daa38a47ef74a115d8483aec3cbed52fece448324ab6568a5e1dab5ad7"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e40e67dbd27650ef10ec1f0957278005f0fd3fbf3543ec42e69dd56a03f8b97a"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc61a08b6f7a7bec2bd73e26233122286cc6eb7714ee542030857c7e8d1ecf32"
      url "https://github.com/hearthroom/cli/releases/download/v#{version}/hearthroom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hearthroom"
  desc "Command-line client for Hearthroom character cards"
  homepage "https://hearthroom.club"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hearthroom"
  bash_completion "completions/hearthroom.bash"
  fish_completion "completions/hearthroom.fish"
  zsh_completion "completions/hearthroom.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hearthroom"]
    end
  end

  # No zap stanza required
end
